export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_START = 'FETCH_START';
export const FETCH_ERROR = 'FETCH_ERROR';

export const FETCH_MORE_PICS = 'FETCH_MORE_PICS';
export const FETCH_MORE_PICS_SAGA_START = 'FETCH_MORE_PICS_SAGA_START';
export const FETCH_MORE_PICS_SAGA_SUCCESS = 'FETCH_MORE_PICS_SAGA_SUCCESS';
